# Disable plaintext auth unless SSL/TLS is used.
disable_plaintext_auth = yes
auth_mechanisms = plain login

# Disable system (PAM/passwd) authentication; use vpopmail SQL instead.
!include auth-sql.conf.ext
